name: Docker Build and Push

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container registry
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: $GITHUB_TOKEN
          

      - name: Build Docker image
        run: |
          docker build --network host -t ghcr.io/${{ github.repository }}:latest -f Dockerfile.cpplint .
        #   docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest